### ISSUE TITLE
Uninstalling Fluent Search does not remove FluentSearch.FileIndexer service

### ISSUE THREAD

**Issue by prakharb5** [adirh3/Fluent-Search#1053]
**Describe the bug**
After uninstalling Fluent Search, I should expect all the files to be removed. But the File Indexer service and related files are still present on the system.

**To Reproduce**
1. Install app
2. Install file indexer addon
3. Uninstall app
4. Notice file indexer still present in Services.

**Expected behavior**
All the files should be removed.

**Screenshots**

![image](https://github.com/adirh3/Fluent-Search/assets/51435948/5a1e21d6-fd80-4bc5-849b-ccedcb28ef6a)

**Desktop (please complete the following information):**
 - Window 11 Version: 23H2
 - Fluent Search Version: 0.9.92.78 **(UNINSTALLED)**
 - Installation source: Microsoft Store

**Additional context**
Just noticed that I had uninstalled this a long time back, but noticing the residual files now. Please let me know if it was patched in newer versions.

**Comment by adirh3** [comment]
@prakharb5 I apologize for the inconvenience, thanks for reporting this.
I am aware that when installed from Microsoft Store, the custom uninstaller of Fluent Search may not kick in if it's uninstalled while Fluent Search is closed.
I am working on a solution that will be available with the next version.

**Comment by DrAnonym666** [comment]
> [prakharb5](/prakharb5)

@prakharb5 @adirh3 

Hi. Based purely on my own experience, I generally recommend uninstaller software. I can tell you purely from experience that almost every uninstalled program leaves behind remnants. Sometimes more, sometimes less.
The 3 hidden folders -Local -LocalLow -Roaming under C:\Users\USERNAME\AppData\ are particularly troublesome if you ignore them. But sometimes program or game files are also hidden in the registry or in the Windows folder.

I can wholeheartedly recommend this program to you: https://github.com/Klocman/Bulk-Crap-Uninstaller

No. It's not self-promotion. I only came across it a month ago. I always used Revo Uninstaller, but you're not doing anything wrong here. Um, well. Yes. Of course, you can also destroy your system if you delete the wrong things ^^ But luckily it offers a restore point + registry backup.

Before I forget. The service you mentioned was removed for me. At least the program wanted to restart because of the service. After the restart it disappeared :-)

Is this service really necessary? Unfortunately I had to delete "Fluent Search" again. I switched to a competitor. I missed the German language :( You can still use it, but I'm trying to make it as consistent as possible. Surely German translation can be done in this day and age with translators and the like?
