### ISSUE TITLE
Mouse-focus for FS on multiple monitors.

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#16]
For multi-monitor setups, create setting to have FS to show on monitor where the mouse is currently placed. This is invaluable for those with multiple monitors

EDIT: Listary,  Alfred and FlowLauncher already do this.

**Comment by samwzlim** [comment]
This is essential for those working with a multi monitor setup! At the moment, Fluent Search can only be configured to show on the main monitor, which is a dealbreaker because that means whenever I work on my secondary monitor(s), I have to look at my main monitor to initiate something with fluent search, which affects your flow.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.55

**Comment by Metroid-Prime** [comment]
confirmed. Feature added!! TY Adir!! closing

@samwzlim

**Comment by Metroid-Prime** [comment]
Unfortunately this broke in .85. No changes were made to settings and it's no longer functioning. I can't even find the setting anymorre.
