### ISSUE TITLE
Autobackup

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#18]
Allow FS to auto-backup settings into a folder. Portable mode would obviously backup into the portable data directory in a folder called "Backup". The user should have a setting to control the # of backups and the frequency of backups (every ___ days)

6/5/21 - Adding Proposed design + settings.  Feedback welcome!
![image](https://user-images.githubusercontent.com/1836362/120913983-ced95e00-c64f-11eb-9c68-7827db453a03.png)

**Comment by samwzlim** [comment]
I separate my Windows machine into 2 user accounts, work and personal. It would be great to have an auto backup/sync feature so I don't have to manually make changes on each account whenever I switch between user accounts!

**Comment by MakeshVineeth** [comment]
Not just Settings, but also the Machine Learning Profile. Since FS learns a lot from our usage using ML, it would be good to also backup the ML learning progress.

**Comment by adirh3** [comment]
@Metroid-Prime Just wondering what do you mean by "sync"? for backup I understand its option to keep additional folder of settings/ml training.
Also @samwzlim I'd recommend you using the portable version since it will read settings from the directory it's already in, this will allow you to have the same settings/data for multiple accounts.

**Comment by Metroid-Prime** [comment]
@adirh3  I think @samwzlim  made the comment about sync.   Sam - what did you mean by that?

**Comment by hpr1999** [comment]
I can't say what @samwzlim meant, but personally, I could also see a lot of value in a way to optionally synchronize FS-settings via some kind of cloud service, or something like OneDrive/GDrive. Personally, I'm using FS on 3 devices now, which already makes manual synchronization a bit annoying. 

A more manual way of doing that might be allowing the user to choose their settings-directory. (So they can use their own cloud backup) 
I suppose, this might be possible with a portable version that is completely stored on a backup, but that has downsides, especially for potentially improving the sync.
Also, as a user, I'd be quite nervous updating the App in case my settings get invalidated or something like that.

**Comment by MakeshVineeth** [comment]
Just sharing some options for cloud storage:

- Visual Studio Code and some extensions uses GitHub to synchronize data, it can also be an option. There can be no privacy risk here as a private repository/Gist will be created in user's own GitHub account and store data in it. Example: [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) extension.
- OneDrive, default available for almost everyone who use Fluent Search, because Windows 10.
- Google Drive with Browser Login, since most people may already have atleast one Google account logged into their browsers.

**Comment by hpr1999** [comment]
I agree with all of those.
I suppose some more privacy-centred people won't like any of those options, but then again, they will probably just _not_ enable the feature anyway.

**Comment by MakeshVineeth** [comment]
Agreed, people can disable the Online Sync feature if not needed 👍

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.60

**Comment by MakeshVineeth** [comment]
I could not get it work. Here is what happened:

- Clicked **Sync now** and a Login window appeared but behind the FS because of **Show at top most** option.
- Closed the Login window through Taskbar thumbnail preview, disabled that **Show at top most** option and tried to sync again.
- Now the login window is no longer appearing even after restarting the FS (Probably some limits on how many times to ask for login? Not something I know).

**Comment by Metroid-Prime** [comment]
Do we have to sync with OneDrive?   Can we have an option to have local backup, especially for portable installs?

**Comment by MakeshVineeth** [comment]
> Do we have to sync with OneDrive? Can we have an option to have local backup, especially for portable installs?

Yes, we have export settings option too in latest version.

**Comment by adirh3** [comment]
> Do we have to sync with OneDrive? Can we have an option to have local backup, especially for portable installs?

What do you mean by local backup? All settings already in the `Blast` directory next to the portable exe, would you like it to export it to a secondary directory?
If so I don't really understand why would you want that..

**Comment by Metroid-Prime** [comment]
> > Do we have to sync with OneDrive? Can we have an option to have local backup, especially for portable installs?
> 
> What do you mean by local backup? All settings already in the `Blast` directory next to the portable exe, would you like it to export it to a secondary directory?
> If so I don't really understand why would you want that..

If you look at the screenshot in the opening post, that was actually taken from aText.  A lot of apps have local backups so that if your settings get corrupted or if you need to potentially revert to a previous version, one is able to.  Each backup specified would have folders stamped with the date.

**Comment by MakeshVineeth** [comment]
Faced some bugs with Online Backup feature as of **0.9.88.70**:

- Manual Sync sometimes doesn't work on first try, have to click Sync now twice.
- Status of Sync now sometimes will be Never synced even if it was able to create folder **.Fluent_Search_Settings** on OneDrive.
- Exiting from FS Tray taking bit more time than before when Sync is enabled.
- Sometimes, manual sync settings will disappear on continuous toggling of Sync settings as shown in below picture.

![unknown.png](https://user-images.githubusercontent.com/19371684/125310670-6ec19000-e350-11eb-9386-e752719bf03e.png)

**Comment by MakeshVineeth** [comment]
Following has been sent to @adirh3 in PM, but again here as this needs to be tracked due to relevance of this issue.

Looks like whenever we close FS from Tray, it just hides the tray icon and syncs in the background, then closes completely. I felt this because after the tray icon disappeared, if we immediately launch the FS, Search window will get displayed right way, completes syncing and closes again by itself. I'm not sure if this is good or bad idea, FS should close immediately when we exit from Tray.

**Comment by Metroid-Prime** [comment]
> Following has been sent to @adirh3 in PM, but again here as this needs to be tracked due to relevance of this issue.
> 
> Looks like whenever we close FS from Tray, it just hides the tray icon and syncs in the background, then closes completely. I felt this because after the tray icon disappeared, if we immediately launch the FS, Search window will get displayed right way, completes syncing and closes again by itself. I'm not sure if this is good or bad idea, FS should close immediately when we exit from Tray.

@MakeshVineeth  FYI I am not able to reproduce this.

**Comment by MakeshVineeth** [comment]
> > Following has been sent to @adirh3 in PM, but again here as this needs to be tracked due to relevance of this issue.
> > Looks like whenever we close FS from Tray, it just hides the tray icon and syncs in the background, then closes completely. I felt this because after the tray icon disappeared, if we immediately launch the FS, Search window will get displayed right way, completes syncing and closes again by itself. I'm not sure if this is good or bad idea, FS should close immediately when we exit from Tray.
> 
> @MakeshVineeth FYI I am not able to reproduce this. I have FS to close indexer upon quitting in latest betas and it's closing pretty soon after right click> exit from tray.

Yeah, this issue got fixed in the latest updates.

**Comment by Metroid-Prime** [comment]
IMO there's still immense value for the portable users of Fluent Search.  I am finding myself having to make local portable backups of FS in case something goes wrong with my settings.

Retuning FS is a royal nightmare (especially web search!) for some.

**Comment by adirh3** [comment]
The sync issues have been fixed.
Back-up locally is not planned atm, feel free to create a new issue for it.
