### ISSUE TITLE
Add a toggle to always run FS as administrator

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#223]
This has been suggested by ltuxer on Discord. Now that we can assign Win key as shortcut, have an option to make FS always run as administrator, just like in PowerToys. So that it can work properly even if focused process is running with admin rights.

PS: Posting it here for tracking.

**Comment by Metroid-Prime** [comment]
I believe this can already be done externally as a workaround

![image](https://user-images.githubusercontent.com/1836362/126058472-f65923ce-e6a7-4275-8dcb-424f2d27e691.png)

**Comment by MakeshVineeth** [comment]
> I believe this can already be done externally as a workaround
> 
> ![image](https://user-images.githubusercontent.com/1836362/126058472-f65923ce-e6a7-4275-8dcb-424f2d27e691.png)

For now, this workaround can be used until we have the direct option.

**Comment by ikjadoon** [comment]
This feature would be useful.

Perhaps Fluent Search could also notify users that their hotkey combination will not allow Fluent Search to be focused as, without stumbling onto this issue, I may not have known about this limitation.

It seemingly can be done with the *.exe itself, though I'm curious if that means users will need to hit a UAC prompt at every reboot.

https://i.imgur.com/p3iDivL.png

**Comment by Metroid-Prime** [comment]
I don't need this at all, but I agree it would be a useful feature.

**Comment by adirh3** [comment]
Running Fluent Search as administrator is not recommended, since anything that FS opens will run as admin as well.
Fluent Search is used to open apps, files, scripts, etc, I'd like to avoid encouraging users opening various apps and files with admin privileges.
If someone needs to run FS as admin and they know what they're doing, they can do as suggested above.

Closing, thanks!
