### ISSUE TITLE
Directory Opus integration 

### ISSUE THREAD

**Issue by matthiashaldimann** [adirh3/Fluent-Search#260]
Support Directory Opus the way Listary does. 
Current Fluent Search behavior:

1. You are in a Directory Opus window, which typically shows two folders (left/right; top/bottom)
2. You use  Fluent Search to find a folder and choose "open" or to find a file an choose "open directory"
3. Fluent Search opens a new Opus windows at this location

Suggested behavior: 
In Step 3., Fluent should not open a new window, but change the directory in the active pane of the active Directory Opus window.

The same would of course also be useful in Total Commander.

**Comment by MakeshVineeth** [comment]
Hey there, this is already possible in Fluent Search. Just you have to give the application path and arguments. Please go to FS Settings > Files. Find the settings for **Default file manager** and change the fields as below:

**Path:** `C:\Program Files\GPSoftware\Directory Opus\dopusrt.exe
`

**Arguments:** Following are different arguments for different behaviors, Choose the one you prefer.

`/cmd Go NEWTAB PATH="%1"` in order to open folder in existing lister.
`/cmd Go "%1"` to change the active pane of lister instead.
`/cmd Go NEW PATH="%1"` to open a new window (default behavior).

**Comment by matthiashaldimann** [comment]
Awful, thanks! With `/cmd Go path="%1"` I get exactly the behavior I was looking for.
