### ISSUE TITLE
File Dialog Context search can't open files

### ISSUE THREAD

**Issue by TheFireRed** [adirh3/Fluent-Search#286]
**Describe the bug**
I cannot open files via the File Dialog Context search.

**To Reproduce**
1. Open a File Dialog (Image Editor > Open)
2. Search for a file either by invoking Fluent Search or by using Instant Search (`filename.png`) and select it
3. Explorer doesn't open the file in File Dialog by context

**Expected behavior**
Explorer should open the file as [seen in this video](https://discussion.listary.com/t/listary-6-beta/4615/715).

**Desktop**
- Windows 10 21H1 19043.1202
- Fluent Search 0.9.88.9989

**Additional context**
My Windows installation is in Spanish (Spain).

**Comment by adirh3** [comment]
Hey @TheFireRed thanks for reporting this and including a video (I removed it for you since it may contain personal information).
There seem to be an issue with this feature when installed on Windows with Spanish as default language, it will be fixed in the next version (will post here once it's ready on nightly).

**Comment by TheFireRed** [comment]
Thanks a lot!

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.89.87

**Comment by TheFireRed** [comment]
Updated to version 0.9.89.87 and tried this too. This is also working! Thanks a lot!
