### ISSUE TITLE
Does not update – Install and Relaunch not working

### ISSUE THREAD

**Issue by hced** [adirh3/Fluent-Search#339]
**Describe the bug**
Fluent informs about an update that's available. Clicking Update/Install doesn't update the program.

**To Reproduce**
1. Open Fluent.
2. Wait for Update Available screen (assuming you have an outdated version).
3. Click on Download/Install.

**Expected behavior**
A new updated version opening up.

**Actual behavior**
The Update Available screen reappears and clicking the Download/Install leads to an endless loop without updating the app.

**Screenshots**
![Snag_1900a03d](https://user-images.githubusercontent.com/93350/138256618-933584e2-0a8b-4018-af33-e27278820537.png)

![Snag_1900b414](https://user-images.githubusercontent.com/93350/138256630-d44cd3f7-201f-459a-8e88-d5510e8cf54c.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1 (OS Build 19043.1288)
 - Fluent Search Version 0.9.88.9989 <-- Portable

**Comment by adirh3** [comment]
@hced Do you use the portable/appx/exe version?

**Comment by adirh3** [comment]
> Wild speculation, why portable update doesn't work, could be that the `FluentSearch.FileIndexer` service might stands in the way of replacing the `FluentSearch.exe` executable.
> 
> If I quit FluentSearch from the sys-tray by right-clicking it, then `Exit`, the app quits but the old executable isn't possible to be replaced by a new downloaded one, because of said service (FluentSearch.FileIndexer) still running.

When updating it should stop the indexer, in some cases it doesn't stop causing the issue you're experiencing, it should be fixed in 0.9.89
As for the downloads, you're right it's confusing, the Github page it shows nightly builds (not stable), I will update it to be clearer, thanks!

FYI Fluent Search and the indexer are communicating through IPC, so there is no need to use elevated mode to stop the indexer.
