### ISSUE TITLE
Match diacritics while searching

### ISSUE THREAD

**Issue by Nuno69** [adirh3/Fluent-Search#388]
**Is your feature request related to a problem? Please describe.**
Fluent search does not match diacritics while searching. As a simple example, let's imagine I am searching for the word "cześć" which means "glory" in Polish. According to the rules of the Polish alphabet, "ś" matches to "S" as "Ś" is just S with an acute, the same follows with "Ć" which matches to "C". According to this example, searching for the word "Czesc" should yield the same result. And while this is not extremely useful (if I type Polish I shall have the Polish keyboard) there's a much more practical use for that. Since Russian has a straight romanization rule, programs like Everything can match cyryllic letters to their latin counterparts. Let me give an example. I have the following file: 12. Комбат.mp3
In order to find it, I have to type the cyryllic directly. But having the russian files on my hard drive doesn't automatically imply my system is able to type russian.
**Describe the solution you'd like**
I wish Fluent Search had an option for optional diacritic matching. I understand the performance cost of using such a feature would be substantial, hence I think the setting should be turned off bt default.

**Comment by IgnusG** [comment]
I'd also like this feature. This problem is prominent in pretty much all languages outside of English. In Europe in particular where people often move from country to country and have to deal with a lot of languages and by extension their writing system - like having french accents, german sharp-s or greek letters. For simplicity, all of these (on most "systems") match their latin counterparts.

I assume there already is a package that should be able to do this conversion (localization is a beast to do right on its own). If the indexer does this conversion before hand and stores it along the original name it should be fairly resource efficient (but this is just a guess as I'm not familiar with how it's implemented).

I wonder though how far the rabbit hole of this task goes. If there is a solution to transform any characters into their latin counterparts (including exotics like persian or chinese) it would be ideal.

**Comment by adirh3** [comment]
@IgnusG can you give me any Persian/Chinese example? like search term and matches

**Comment by Nuno69** [comment]
争渡 (Zheng Du) should match
 - 争渡读屏青春版 2022 贺岁版 1.6.3.1 争渡公告 争渡网, http://www.zd.hk/thread-107248.htm, 1 out of 16
 - 争渡读屏文本预处理API.txt, C:\Users\Nuno\Documents\Tencent Files\2734513668\FileRecv\X-ZDSR1624P16\ZDSRNew\addins\争渡读屏文本预处理API.txt, 4/27/2020 12:03 PM, 830 Bytes, 3 out of 15
 - 争渡读屏文本预处理API.txt, C:\Users\Nuno\Documents\Tencent Files\2734513668\FileRecv\X-ZDSR1630-0112\ZDSRNew\addins\争渡读屏文本预处理API.txt, 4/27/2020 12:03 PM, 830 Bytes, 6 out of 15
Same with d读屏 (Du ping). Please keep in mind that "Du" can match also “度“ so CHinese characters which are written in the same way in latin can, and most probably will have different representation in hanzi.
So for example "Ma" can mean Mother, horse or a question sign

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.9993
