### ISSUE TITLE
add "fetch" and "upload" options for sync

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#392]
**Is your feature request related to a problem? Please describe.**
the deleted tasks will show up after synced.

**Describe the solution you'd like**
add "fetch" and "upload" options for sync. so that we can easy to know what the sync actually doing.

![图片](https://user-images.githubusercontent.com/93647031/146627195-6478617b-46d1-4bc6-8215-d7d51ef4aae5.png)

**Comment by adirh3** [comment]
@u-Sir The returned Tasks was a bug, it was fixed recently (please confirm).
Also, when clicking `Sync now` FS will ask you whether to Fetch or Upload settings if any exists in OneDrive, otherwise it's just uploading your settings to server and pull them on startup only if more up-to-date settings are available.
