### ISSUE TITLE
Issues with Instant Search

### ISSUE THREAD

**Issue by erohtar** [adirh3/Fluent-Search#403]
**Describe the bug**
1. When Instant Search is enabled on an application, it pops up unintentionally, like when pressing an Alt+key combination in the host app.
2. The "Interact with result on focus" setting doesn't seem to work, as in it doesn't select the result in the host app when selected in FS.

**To Reproduce**
You could test the above scenario in several applications, but the ones I tested in were KeePass and a standard AutoHotkey GUI with a ListView control.

**Desktop (please complete the following information):**
 - Windows 10
 - Fluent Search Version [0.9.90.87]

**Additional context**
As discussed in the other GitHub thread

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.91

**Comment by rajat-r** [comment]
That was quick! Really awesome and impressive! 
A slight improvement would be to implement it the way Listary does, so that every time FS interacts with the selected search result in the host window, it does flash because it gained and lost focus for a moment. I think the way Listary does is reading the keys received by the host window (that's why the host window never loses focus), instead of receiving the keys itself and sending to host window.
But either way, this is a major improvement.
I did some testing and I see that while the 'List Item' search works in well now in both KeePass and AutoHotkey, the 'Text' search that also looks for values in columns other than first, is not able to Go To the row correctly in KeePass (works in AutoHotkey though).

**Comment by adirh3** [comment]
@rajat-r Thanks for the explanation.
I will try improving it as you suggested, but can you please explain why should the host window keep the focus?
One thing I never fully understood when Listary users asked for this feature is the use case, which is the reason the implementation is lacking.
It would really help me if you could please describe some of the scenarios you use this feature, thanks!

**Comment by rajat-r** [comment]
> why should the host window keep the focus?

Oh it doesn't need to be/stay in focus, just the constant flashing of the host window as you traverse through the result list is jarring - so that's why I suggested doing it the Listary way as a solution. Using it with Listary it has always felt very smooth and natural.

> It would really help me if you could please describe some of the scenarios you use this feature

Of course, so there are countless applications out there that have some sort of data displayed in lists in their interface. And a lot of them don't have built-in search into this list, or it's not implemented in the most convenient way. Having a consistent way to look through such lists that works across applications is amazing! Does that help?

**Comment by adirh3** [comment]
> > why should the host window keep the focus?
> 
> Oh it doesn't need to be/stay in focus, just the constant flashing of the host window as you traverse through the result list is jarring - so that's why I suggested doing it the Listary way as a solution. Using it with Listary it has always felt very smooth and natural.
> 
> > It would really help me if you could please describe some of the scenarios you use this feature
> 
> Of course, so there are countless applications out there that have some sort of data displayed in lists in their interface. And a lot of them don't have built-in search into this list, or it's not implemented in the most convenient way. Having a consistent way to look through such lists that works across applications is amazing! Does that help?

Thanks for the input!
For the use case I was talking about whether the host app/FS should keep the focus, but I understand now that it doesn't really matter as long as it's smooth.
Will improve this in the next update, thanks!

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.91                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by erohtar** [comment]
Thanks Adir! It's not flashing anymore.

Btw is there a way for FS to only show the list items by default (at least when that was the in-focus control when FS was invoked)? As you can see in the screenshot, right now it gives multiple entries for essentially the same result, and text match is on top.

![image](https://user-images.githubusercontent.com/5120628/234003912-8438b1f3-8f7e-4309-a559-688ef686a745.png)

A possible way this could be implemented - when listview/listbox control is in focus when FS is invoked, then all the matching list item results are in the top group of results, followed by the matching text anywhere group of results.

**Comment by adirh3** [comment]
@erohtar I apologize for not replying I had hard time managing issues here.
As the original issue is resolved, if you still want another feature (described by your last comment) please open another issue for it.

**Comment by erohtar** [comment]
Thank you Adir!
