### ISSUE TITLE
Very regularly, Fluent Search opens without having the focus

### ISSUE THREAD

**Issue by Elaws** [adirh3/Fluent-Search#406]
**Describe the bug**
When launching Fluent Search through keyboard shortcut, it regularly does not have focus, so that you can't directly start typing but need to first click with the mouse to activate it.

**Desktop (please complete the following information):**
 - Windows 10 Version:  20H2

**Comment by adirh3** [comment]
@Elaws thanks for reporting this issue.
Which hotkey do you use for activating Fluent Search?
Also, which version of Fluent Search do you have? (you can check that in the about window)

**Comment by Elaws** [comment]
Thanks for your quick reply @adirh3 : hotkey used is "Ctrl + Ctrl". Fluent Search version is 0.9.89.9990.

**Comment by adirh3** [comment]
@Elaws can you please check if it happens using a different hotkey? 
Ctrl+Ctrl is a bit problematic since it is not hooked by OS, meaning other apps can listen to it as well and try to steal focus (just as Fluent Search does)
When you press Ctrl+Ctrl and Fluent Search loss focus, look at the app you were on before that, that app might have Ctrl+Ctrl invoke something and disabling that might be the best solution.

**Comment by Elaws** [comment]
Oh well, it seems obvious now that I shouldn't have used this shortcut in the first place. I will change my shortcut and hopefully this won't happen again.

Thanks for your time

**Comment by adirh3** [comment]
> Oh well, it seems obvious now that I shouldn't have used this shortcut in the first place. I will change my shortcut and hopefully this won't happen again.
> 
> Thanks for your time

Sure thing, feel free to share any feedback here or in Discord.
Closing this, reopen if you are still experiencing this issue with other hotkeys.
