### ISSUE TITLE
High Priority: Web Searches broken

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#50]
**Describe the bug**
Web searches are not triggering even if they're enabled.  It might have broke the version _before_ 0.9.85.1

**To Reproduce**
1. Type "g <search string> 
2. Observe that FS doesn't search google.
 
I have google in web search: 
![image](https://user-images.githubusercontent.com/1836362/120916906-41066e80-c661-11eb-986d-8531bb302345.png)

Search turned on:
![image](https://user-images.githubusercontent.com/1836362/120916910-4663b900-c661-11eb-8e08-be539be0a6be.png)

**Expected behavior**
Google search should be triggered

**Screenshots**
Instead, I get this:
![image](https://user-images.githubusercontent.com/1836362/120916925-58ddf280-c661-11eb-8c46-74e79fa1f660.png)

100% reproducible

**Desktop (please complete the following information):**
 - Windows 10 LTSC  v1809
![image](https://user-images.githubusercontent.com/1836362/120916950-6dba8600-c661-11eb-8620-5bf19d1d2deb.png)

 - Fluent Search Version [e.g. 0.9.85.1] although it might have broken version before.

**Comment by mochigithub** [comment]
Closing this issue as it's reported under issue #46

**Comment by Nomad-0** [comment]
facing the same

**Describe the bug**
I have added several `tag`s to some web search URLs e.g. `gg` for Google, `yt` for Youtube, 
![image](https://user-images.githubusercontent.com/76395594/120915979-a17cc680-c6c8-11eb-8836-7d7953a206db.png)

but no tags are shown if I type gg, yt, or several other web search tags. however, tags appear if I type the `Name` of the urls
![image](https://user-images.githubusercontent.com/76395594/120916015-cbce8400-c6c8-11eb-8409-257c03a914dd.png)
![image](https://user-images.githubusercontent.com/76395594/120916231-38964e00-c6ca-11eb-95ab-f35b46e71e81.png)

**To Reproduce**
add a short tag to a web search URL
open fs
try to type the short tag, press `tab` (your `insert tag key`)

**Expected behavior**
when I type the tag and press tab, the tag would appear

**Desktop (please complete the following information):**
 - Windows 10 Version: [21H1]
 - Fluent Search Version [0.9.85.1]

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.20

**Comment by Metroid-Prime** [comment]
> This issue has been potentially fixed in version 0.9.85.20


Per changelog: - Fixed a bug that search tags did not apply when the tag was different than it's name (e.g. Web searches) #50


Can confirm fix. @Nomad-0  if you're able to confirm as a high priority issue as your earliest convenience. Closing ticket

**Comment by Nomad-0** [comment]
yes, it's solved on my end too. confirmed.
