### ISSUE TITLE
Fluent Search not fully Searching all files

### ISSUE THREAD

**Issue by miguelnarayan** [adirh3/Fluent-Search#570]
**Describe the bug**
I'm trying to search for document files using Fluent Search, but it doesn't return any. I have a few documents that used to be retrievable through Fluent Search, and it made my life easier, as it'd look for files both in OneDrive and in my PC disks. Nowadays, I don't know what happened, but it only shows a few .exe files. All the JPGs, PDFs, and any other files that aren't exe are not returning in searches, even some .exe files don't show up, only a few do.

**Expected behavior**
Once I'd type any prefix, suffix, or a part of the name of a file I wanted to retrieve through Fluent Search, I was expecting it'd return a list of files that'd somewhat match what I had just started typing... like suggestions for what I am searching...

**Desktop (please complete the following information):**
 - Windows 10 Version: [e.g. 21H2]
 - Fluent Search Version [e.g. 0.9.90.9999]

**Comment by adirh3** [comment]
@miguelnarayan please check that your file indexing settings are configured as you need, in Settings -> Files 
<img width="606" alt="image" src="https://user-images.githubusercontent.com/27368554/166900673-35e7be9f-f2e5-4670-9489-edd8f04f3a8d.png">

Make sure you're using the Fluent Search indexer, and the desired drives are set to the index.

Also, there is an issue with indexing of OneDrive files in the stable version and is fixed in the nightly version.
If you can't find some files in OneDrive folder you can update to the nightly version by changing the Release feed in Settings -> System.

**Comment by aagha** [comment]
What's the frequency with which the indexer updates?

I'm noticing that when I create a file or rename one, they're not showing up with Fluent Search for up to 30 minutes, while Listary is finding them within a few minutes.
