### ISSUE TITLE
Suspend in certain software

### ISSUE THREAD

**Issue by qstdnx** [adirh3/Fluent-Search#594]
**Is your feature request related to a problem? Please describe.**
There are a lot of shortcut key settings in fluentsearch, which will inevitably conflict with some software or game shortcut keys, so I can only turn off fluentsearch to avoid conflicts.

**Describe the solution you'd like**
1.Simple: provide a shortcut key to temporarily turn off / reopen all shortcut keys
2.Advanced: FC provides users with settings to deactivate all keyboard shortcuts while using a certain software.

**Comment by adirh3** [comment]
@qstdnx thanks for the feedback, I understand you want to completely disable the hotkey and not just make Fluent Search ignore it?
The issue with temporarily unregistering a hotkey is that when you register it again it may not be available.

Currently there are three ways to ignore hotkeys - 
1. `Enable Gaming mode` in the system tray menu which ignores all hotkeys and disables background processing
2. `Ignore hotkey on foreground processes` in Settings -> Power User, which ignores hotkeys on per process basis
3. `Ignore hotkeys on full screen processes` in Settings -> Power User (nightly builds), good for games

If your use case is games, I believe ignoring hotkeys is sufficient, since games do not register hotkeys by themselves, they simply listen to keyboard events.
Otherwise, I would appreciate it if you could explain a scenario in which you must fully unregister a hotkey.

**Comment by qstdnx** [comment]
@adirh3 I'm sorry. I think **ignore hotkey on foreground processes** is what I want. I ignored it when I set up FS and wasted your time here. Even if there are software registrate shortcuts that conflict with FS, most of those software and FS shortcuts can be modified, so that's enough to use now.

**Comment by qstdnx** [comment]
@adirh3 A weird bug, I set the shortcut key for **In-app search** to  **Alt+q**, **Search hotkey** to **ctrl+q**. I have no problem using **ctrl+q** when playing games that I have ignored, but it doesn't trigger properly when I use **Alt+q**. This is also happened  in **gaming mode **.
The game I played is **Age of Empires III Definitive Edition**, which is a RTS game that needs a lot of shortcut keys to assist in playing.

**Comment by adirh3** [comment]
> @adirh3 A weird bug, I set the shortcut key for **In-app search** to **Alt+q**, **Search hotkey** to **ctrl+q**. I have no problem using **ctrl+q** when playing games that I have ignored, but it doesn't trigger properly when I use **Alt+q**. This is also happened in **gaming mode **. The game I played is **Age of Empires III Definitive Edition**, which is a RTS game that needs a lot of shortcut keys to assist in playing.

Interesting, I checked using AutoHotkey and seems like all key events are present when using Alt+Q on my machine. What happens is probably when pressing Alt+Q another key is being pressed alongside it, which cause it to not trigger the game.
If you can send me your settings files in Discord PM I can check what's causing it. The settings are in `%appdata%\Blast\Settings`

**Comment by qstdnx** [comment]
@adirh3 I just tried again, and it couldn't be triggered.
Open FS
![1](https://user-images.githubusercontent.com/20844622/169682483-cf78f16b-d815-4274-96e8-e0db310d406d.gif)
Close FS
![3](https://user-images.githubusercontent.com/20844622/169682564-71c01939-dff1-4c2b-aac6-d8a1def44006.gif)
setting
[Settings.zip](https://github.com/adirh3/Fluent-Search/files/8748936/Settings.zip)

**Comment by adirh3** [comment]
Thanks @qstdnx will check it, I deleted your comment because the Settings files may contain personal information.
Next time please send me it in Discord/mail.

**Comment by qstdnx** [comment]
Thanks.(͡° ͜ʖ ͡°)

**Comment by adirh3** [comment]
@qstdnx I can't seem to repro this, when pressing Alt+Q I see all keys behind pressed in AutoHotkey -
![image](https://user-images.githubusercontent.com/27368554/169705303-efa03ae0-ec63-4991-988b-d1c9ad8ce0ad.png)
It probably means that this games tries to hook the hotkey of Alt+Q, can you do a test - unregister Alt+Q in FS, then start the game press Alt+Q, and then try to register Alt+Q again in FS

**Comment by qstdnx** [comment]
@adirh3 removing the hotkey Alt+q, Alt+q can be used normally in the game, and re-register Alt+q in the running state of the game, It can't be used properly in the game.
