### ISSUE TITLE
Building file index takes too much time

### ISSUE THREAD

**Issue by Meieraa** [adirh3/Fluent-Search#622]
It seems FS will rebuild file index every time we reboot the computer. It takes too much time. And during this time, the file searching result is incompleted. 
Am i lost something in setting that can slove this.

**Comment by Meieraa** [comment]
Im in portable nightly version

**Comment by adirh3** [comment]
Thanks @Meieraa, I will make it possible to still search while it's indexing.
Just wondering, how long does it take to index for you? And how many drives do you index?

I have made a few changes to indexing in the nightly that increase index time, but improves search speed by a lot.

**Comment by adirh3** [comment]
Thanks @Meieraa, I will make it possible to still search while it's indexing.
Just wondering, how long does it take to index for you? And how many drives do you index?

I have made a few changes to indexing nightly that increase index time, but improves search speed by a lot.

> thank you for relplyling so soon @adirh3 . 5 partition from two drives. And it takes nearly 5 minute. it's a little bit long for me. hope it helps for you.
> 
> And just for advise, i think files like index should be updating weekly or by users choice. Index changing do something to index file to fix the accuracy so that we need't rebuilding it so frequently.
> 
> If something reckless, forgiving my poor English.Thanks again.

Thanks for the feedback!
So, you would like to have an option to make indexing manually/scheduled?
The FS indexer is designed to always have an up-to-date index, that's why it indexes every time it starts to make sure the index is up to date.
If the indexer will not do that then you will not find new files and deleted files will still show, would you be OK with that?

**Comment by Meieraa** [comment]
Make sense. I'm too idealistic.
Maybe I should reduce the number of index path.
but still hope you can make good balance between the accuracy of the index and search speed 
Anyway FS is a good software. I’ll stay my interest on that, thanks

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.992                                        . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by Meieraa** [comment]
This completely solved the problem
