### ISSUE TITLE
Ignore hotkey on fullscreen processes setting consumes some of the inputs

### ISSUE THREAD

**Issue by tomas-hotovy** [adirh3/Fluent-Search#685]
**Describe the bug**
I have my Fluent search mapped to ctrl + space. I have the "ignore hotkey on full screen processes" enabled. When I press the Ctrl + Space in one of the fullscreen applications the Ctrl is detected by that app, but the space not. So the Fluent search consumes the second input. When I press Ctrl or Space separately, both are recognized by the app. When I exit the Fluent Search Ctrl + Space starts working as expected. Most likely this bug happens with any input with a modifier key, but I have yet to test this. 

**To Reproduce**
1. Map your Fluent Search to Ctrl + Space
2. Enable "ignore hotkey on full screen processes" setting
3. Open any fullscreen application where you have Ctrl + Space mapped to something.
4. Press Ctrl + Space while in that application

**Expected behavior**
Fluent Search does not consume the second input (Space), Therefore the Ctrl + Space can be mapped in another fullscreen application. 

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H2
 - Fluent Search Version 0.9.92.47

**Comment by adirh3** [comment]
Hey @tomas-hotovy, the `Ignore hotkey on full screen processes` does not un-register the hotkey, it simply ignores it.
The reason is that if it unregistered it when a full screen process was opened, it might not be able to register it again afterward, emptying the hotkey.
I might change this feature to unregister hotkeys completely in full screen apps and when using gaming mode, so keep this open :)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.48                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
