### ISSUE TITLE
Automatic Enabling of Game Mode

### ISSUE THREAD

**Issue by crestofthebeast** [adirh3/Fluent-Search#777]
**Is your feature request related to a problem? Please describe.**
I would love to use fluent search's screen search feature! Apps like warpd and shortcat on unix/mac systems appeal to me greatly as someone with mobility/typing issues, and screen search is the closest I've seen to that in a windows system.

The issue here is that I also play Destiny 2 -- unsure if this is a well-known issue, but there's some infernal background process going on that causes D2 to silent fail (probably an anticheat issue to do with file indexing etc whilst the game is running -- maybe ram access?).
This basically means I... cannot use fluent search.

**Describe the solution you'd like**
The ideal solution, in my mind, is to have screen search bundled into its own separate app. I understand, however, that this isn't always the easiest option for the developer.

The most "implementable" solution (from my perspective) would be the ability to create a list of processes to look for that automatically enable game mode, which I believe fixes the crashes from some cursory googling a while ago.

**Describe alternatives you've considered**
The simplest alternative solution/bodge would be to manually disable game mode **every time** I boot the game, but that's... more than a little bit impossible to do every time.
I'm unsure if a plugin would be able to do this, and could potentially try to hack something together if this issue is out of scope.

**Comment by adirh3** [comment]
@crestofthebeast This is most likely due to In-app content indexing, there are multiple things you can try - 
1. Disable `Search in app content` in Settings -> Processes, this means UI results such as tabs, links, will not show in search (this is unrelated to screen search)
2. Disable your game processes from being indexed in `Ignore these processes for in app content search` in Settings -> Processes 

Also few gaming features you might want to know about - 
1. `Ignore hotkeys on foreground processes`
2. `Ignore hotkeys on full screen processes` which is only available in the nightly build

Also, in the nightly build when any process is ignored through any `Ignore hotkeys on X` Fluent Search will automatically enter a partial gaming mode that only waits for you to switch out of that process.
This feature will be available in the stable release within the next two months and seems to match your request.

Hope this helps, let me know if you have any question.

**Comment by crestofthebeast** [comment]
Hi!
Tried disabling those options, but still got crashes unfortunately. When the partial gaming mode option hits stable, I'll give it a try again. Many thanks for the response!

**Comment by adirh3** [comment]
@crestofthebeast took a while, now it's available in stable.

**Comment by adirh3** [comment]
Closing, feel free to reopen if it doesn't work as you expect.
