### ISSUE TITLE
Support custom window shadow

### ISSUE THREAD

**Issue by Nawbc** [adirh3/Fluent-Search#825]
This is native
![image](https://user-images.githubusercontent.com/45007226/228714472-7f91ff5d-f981-4f90-81e3-58c0dd6e7d0f.png)

This is fluent search 
![image](https://user-images.githubusercontent.com/45007226/228714535-90f6b4bb-36c4-4d95-96c8-a3b6c938a6b3.png)

I think the window shadow is too heavy

**Comment by adirh3** [comment]
You can't really tell from your screenshot but native has a bigger blur radius, that's why the shadow is less "dense" like in FS.
The reason I made it is because Fluent Search is something you usually open above other windows, and I felt like it gives better separation with this kind of shadow.
I will consider adding the option to customize it, but probably not in 0.9.92.x.

**Comment by Nawbc** [comment]
> You can't really tell from your screenshot but native has a bigger blur radius, that's why the shadow is less "dense" like in FS.
> 
> The reason I made it is because Fluent Search is something you usually open above other windows, and I felt like it gives better separation with this kind of shadow.
> 
> I will consider adding the option to customize it, but probably not in 0.9.92.x.
Yep. I forgot that i modified the registry. my bad.
