### ISSUE TITLE
Menu display is incomplete

### ISSUE THREAD

**Issue by liujvnes** [adirh3/Fluent-Search#992]
**Describe the bug**
![屏幕截图 2024-04-09 203734](https://github.com/adirh3/Fluent-Search/assets/25132014/675333c9-a3c7-4338-9ce1-2ec54e1ef9f4)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Window 10/11 Version: [e.g. 24H2]
 - Fluent Search Version: [e.g. 0.9.80.0]
 - Installation source: Installer / Microsoft Store / Portable / Appx

**Additional context**

**Comment by xiyg33** [comment]
Maybe you could update FS version to 1.0.0.39 now, I remember that I experienced this bug in the old version yet disappear now. My way to adapt to this bug is that click right the `show` button then it may show entire menu. ~~Maybe it's useless😶‍🌫️~~

By the way, you could export your settings form `settings->sync->export` in order to migrate easily.

**Comment by adirh3** [comment]
This should be resolved in 1.0.0.37+, please reopen if not
